# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a483cf9191453233420acf28b6bf9eb375148ab330a0a4dee87ce327f45a0ce01dfd5e6563e68ba302b510da3b41f488e7b90528bb306a152c15998106286888

test:
  secret_key_base: 55428b83488abca11f9994a6e1ab0da08b084cb72b686b570348691c67ba930e958743d6b137e6fc1bb3fb64abd6747d593ae308228f80ea4eab05bc9c91b517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
